name: "522-temp"

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11.14
  - numpy=1.26.4
  - ipykernel=7.1.0
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - altair=6.0.0
  - vl-convert-python=1.8.0
  - pyarrow=22.0.0
  - ucimlrepo=0.0.7
  - jupyterlab=4.5.0
  - click=8.1.7
  - quarto=1.8.26
  - pip
  - plotnine
  - pip:
      - vegafusion==2.0.3
      - pointblank==0.16.0
      - deepchecks==0.19.1
      - anywidget==0.9.21
      - ipywidgets==8.1.8
      - great-tables[extra]==0.20.0
  

